name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest<% if (db === 'postgresql') { %>
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5<% } %>
    env:
      API_SERVER_PORT: 8080
      API_ORIGIN: http://localhost:8080
      API_BASE_PATH: /api
    steps:
      - uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/cache@v2
        id: client-npm-cache
        with:
          path: "node_modules"
          key: client-npm-${{ hashFiles('package-lock.json') }}
      - uses: actions/cache@v2
        id: server-npm-cache
        with:
          path: "server/node_modules"
          key: server-npm-${{ hashFiles('server/package-lock.json') }}
      - run: npm install
        if: steps.client-npm-cache.outputs.cache-hit != 'true'
      - run: npm install --prefix server
        if: steps.server-npm-cache.outputs.cache-hit != 'true'
      - run: npm run lint<% if (db === 'sqlite') { %>
      - run: echo "API_DATABASE_URL=file:./dev.db" > server/prisma/.env<% } else if (db === 'postgresql') { %>
      - run: echo "API_DATABASE_URL=postgresql://postgres:postgres@localhost:5432/test" > server/prisma/.env<% } %>
      - run: npm run typecheck
      - run: |
          npm run migrate:dev
          npm test
        env:
          API_JWT_SECRET: test_secret
